### ISSUE TITLE
Using wrong options?

### ISSUE THREAD

**Issue by mjanda** [hgoebl/Leaflet.MultiOptionsPolyline#2]
Shouldn't you do
```
this.addLayer(new L.Polyline(segmentLatlngs, multiOptions.options[prevOptionIdx]));
```
instead of
```
this.addLayer(new L.Polyline(segmentLatlngs, multiOptions.options[optionIdx]));
```
?

**Comment by arfa-mcarfa** [comment]
I just started using this today and noticed the options for the line segments are incorrect. I came here to suggest the same fix as above.

It doesn't make sense to use the option set for the new segment when drawing the completed segment.

**Comment by hgoebl** [comment]
Yes, seems to be a bug. Sorry, at the moment I'm very busy. Will fix it asap.
