### ISSUE TITLE
Calling setLatLngs() with a new path doesn't change the value returned by getLatLngs()

### ISSUE THREAD

**Issue by stuckj** [hgoebl/Leaflet.MultiOptionsPolyline#4]
If I initialize a multi-options polyline with a set of lat lng values and change it to a new array of values via setLatLngs the map will reflect the changes, but the result from getLatLngs() will be the original array. This seems like undesired behavior. I think you might have just forgotten to reset _originalLatlngs to the new array in setLatLngs. Yes?

**Comment by hgoebl** [comment]
@stuckj thanks for contributing!

**Comment by stuckj** [comment]
No prob, thanks for the quick update! :)
