### ISSUE TITLE
Does the weight option work on fixed pixel or meter?

### ISSUE THREAD

**Issue by mickeyjohn** [hgoebl/Leaflet.MultiOptionsPolyline#9]
Hi,
As I could not find the documentation for all the supported options. Does any one know whether we set the weight as meters instead of pixels in Leaflet L.polyline options?

Thanks a lot.
John.

**Comment by hgoebl** [comment]
I can't find anything like `weight` in the source code.
You might have more luck to ask a question on [StackOverflow](https://stackoverflow.com/).
